name: 构建

# 触发工作流的事件
on: 
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builder_matrix:
    strategy:
      fail-fast: false
      matrix:
        arch: [ x86, x64, arm64 ]
        os: [ ubuntu-20.04, windows-latest, macos-13, macos-14 ]
        exclude:
          - os: ubuntu-20.04
            arch: x86
          - os: ubuntu-20.04
            arch: arm64
          - os: macos-13
            arch: x86
          - os: macos-13
            arch: arm64
          - os: windows-latest
            arch: arm64
          - os: macos-14
            arch: x86
          - os: macos-14
            arch: x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.8.10'
          architecture: ${{ matrix.arch }}
      - name: Setup uv
        uses: astral-sh/setup-uv@v4
      - name: Init zip folder
        run: mkdir zip

      - name: Run Windows build
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          # 下载 zip.exe 工具
          curl -o zip.exe -L http://www.stahlworks.com/dev/zip.exe
          # 创建虚拟环境
          uv venv
          # 激活虚拟环境
          .venv/Scripts/activate
          # 安装依赖
          uv pip install -r requirements.txt
          # 安装 pyinstaller
          uv pip install pyinstaller
          # 使用 pyinstaller 打包应用程序
          pyinstaller main.py `
            -w `
            -i ./resources/SectionIstool_icon.ico `
            -n Sectionlstool `
            --contents-directory . `
            --add-data ./app/resource/icon:icon `
            --add-data ./app/resource/README:README `
            --add-data ./app/Settings:Settings `
            --add-data LICENSE:.
          # 使用 zip.exe 工具将打包好的文件压缩成 ZIP 文件
          ./zip -r -q "zip/Sectionlstool-Windows-${{ matrix.arch }} (Unsigned).zip" dist/Sectionlstool/*

      - name: Run Linux build
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          # 创建虚拟环境
          uv venv
          # 激活虚拟环境
          source .venv/bin/activate
          # 安装依赖
          uv pip install -r requirements.txt
          # 安装 pyinstaller
          uv pip install pyinstaller
          # 使用 pyinstaller 打包应用程序
          pyinstaller main.py \
            -w \
            -i ./resources/SectionIstool_icon.ico \
            -n Sectionlstool \
            --contents-directory . \
            --add-data ./app/resource/icon:icon \
            --add-data ./app/resource/README:README \
            --add-data ./app/Settings:Settings \
            --add-data LICENSE:.
          # 使用系统自带的 zip 工具将打包好的文件压缩成 ZIP 文件
          zip -r -q zip/Sectionlstool-Ubuntu22.04.zip dist/Sectionlstool/*

      - name: Run macOS build
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: |
          # 创建虚拟环境
          uv venv
          # 激活虚拟环境
          source .venv/bin/activate
          # 安装依赖
          uv pip install -r requirements.txt
          # 尝试升级 pyqt5-qt5 版本
          uv pip install pyqt5-qt5==5.15.4 || uv pip install pyqt5
          # 安装 pyinstaller
          uv pip install pyinstaller
          # 使用 pyinstaller 打包应用程序
          pyinstaller main.py \
            -w \
            -i ./resources/SectionIstool_icon.ico \
            -n Sectionlstool \
            --contents-directory . \
            --add-data ./app/resource/icon:icon \
            --add-data ./app/resource/README:README \
            --add-data ./app/Settings:Settings \
            --add-data LICENSE:.
          # 使用系统自带的 zip 工具将打包好的文件压缩成 ZIP 文件
          zip -r -q "zip/Sectionlstool-macOS-${{ matrix.arch }} (bundle).zip" dist/Sectionlstool.app/*
          zip -r -q "zip/Sectionlstool-macOS-${{ matrix.arch }}.zip" dist/Sectionlstool/*

      - name: Upload unsigned application
        if: ${{ ( matrix.os != 'windows-latest' && github.event_name != 'pull_request' ) || github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4.4.2
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: ./zip

      - name: Upload unsigned single file
        if: ${{ matrix.os == 'windows-latest' && github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4.4.2
        with:
          name: windows-${{ matrix.arch }} (Unsigned single)
          path: ./dist/Sectionlstool/Sectionlstool.exe

  release:
    needs: [builder_matrix]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
    with:
      runid: ${{ github.run_id }}